### ISSUE TITLE
Jihyeon Todo

### ISSUE THREAD

**Issue by mic050r** [2023-Test-mate/test-mate-android#155]
- [ ]  홈, 메인편집, 시험기록 API 연동
- [ ]  로그아웃 API 연동
- [ ]  마이페이지 api 연동
- [ ]  햄버거바 눌렀을때 UI 나오도록
- [ ]  햄버거바 관련 API 연동
