### ISSUE TITLE
Seulgi Todo

### ISSUE THREAD

**Issue by mic050r** [2023-Test-mate/test-mate-android#157]
- [x]  앱 시작 전과 이용약관 페이지 넘어가도록
- [x]  회원가입 유효성 검사(값이 null이 아닌지 맞는지 확인)
- [ ]  캘린더 페이지 제작
- [ ]  캘린더 API 연동
- [x]  nav바 이미지들 png → xml
