### ISSUE TITLE
Huihyeon Todo

### ISSUE THREAD

**Issue by mic050r** [2023-Test-mate/test-mate-android#158]
- [ ]  안드로이드 알림 기능 구현
- [ ]  알림 API 연동
- [ ]  오답노트 UI 수정
